name: Process Figma Tokens PR

on: pull_request

jobs:
  run_if:
    if: ${{ github.head_ref == 'figma-tokens' }}
    name: Process Figma Tokens
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@master
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install Dependencies
        run: npm install

      - name: Run token-transformer
        run: npx token-transformer input/src/tokens.json input/src/tokens-input.json --resolveReferences false

      - name: Run style-dictionary
        run: npx style-dictionary build --config config.cjs

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'meliecool'
          message: 'chore: style-dictionary output'
          add: '.'